### ISSUE TITLE
hope wish providing a model file

### ISSUE THREAD

**Issue by endlesscollider** [MIT-SPARK/MiDiffusion#4]
Dear MiDiffusion Developers,

I hope this message finds you well.

First of all, I would like to express my gratitude for providing detailed information and code for the MiDiffusion project.  While following the steps in the documentation to set up the environment and run the project, we noticed that the trained model file (i.e., weight_file) is missing. To thoroughly test and validate the proposed method, and to further advance our research, we kindly request access to a pre-trained model file.

If you could provide the trained model file or detailed instructions on how to train the model, it would be greatly appreciated. This would significantly facilitate our understanding and application of the model.

Thank you for your attention and assistance.

Best regards,

**Comment by SiyiHu** [comment]
We will release example model weights in a week.
