### ISSUE TITLE
CachedThreedFront' object has no attribute '_dataset'

### ISSUE THREAD

**Issue by suny194** [MIT-SPARK/MiDiffusion#6]
python  scripts/generate_results.py，show AttributeError: 'CachedThreedFront' object has no attribute '_dataset'
how to solve? thx

**Comment by SiyiHu** [comment]
I have not seen this problem. Do you know which line of code is causing this error?

**Comment by suny194** [comment]
> I have not seen this problem. Do you know which line of code is causing this error?

has resolved thx~
